// ========================================================================
// MODULE: Persistent Idempotency — ProcessedEvent Collection
// ========================================================================
// Stores every eventId that has been successfully handled by a consumer.
// Used by inventory, payment, and delivery consumers to prevent duplicate
// processing across restarts and multiple instances.
//
// The unique index on (eventId + consumer) guarantees that a concurrent
// insert for the same pair will throw a duplicate-key error — which the
// consumer catches and treats as "already processed".
// ========================================================================

const mongoose = require('mongoose');

const processedEventSchema = new mongoose.Schema({
    // UUID generated by the Kafka producer envelope
    eventId: { type: String, required: true },

    // Which consumer group handled this event (e.g. 'inventory', 'payment')
    consumer: { type: String, required: true },

    // Timestamp of when the event was processed
    processedAt: { type: Date, default: Date.now },
}, { timestamps: false });

// Compound unique index — fast lookup + prevents duplicate inserts
processedEventSchema.index({ eventId: 1, consumer: 1 }, { unique: true });

module.exports = mongoose.model('ProcessedEvent', processedEventSchema);
