services:

 # --- MICROSERVICES ---
  auth-service:
    build: ./auth-service
    image: backend-auth-service
    container_name: minit-auth-service
    ports:
      - "5001:5001"
    env_file: .env
    restart: always

  order-service:
    build: ./order-service
    image: backend-order-service
    container_name: minit-order-service
    ports:
      - "5002:5002"
    env_file: .env
    restart: always

  inventory-service:
    build: ./inventory-service
    image: backend-inventory-service
    container_name: minit-inventory-service
    ports:
      - "5003:5003"
    env_file: .env
    restart: always

  delivery-service:
    build: ./delivery-service
    image: backend-delivery-service
    container_name: minit-delivery-service
    ports:
      - "5004:5004"
    env_file: .env
    restart: always

  payment-service:
    build: ./payment-service
    image: backend-payment-service
    container_name: minit-payment-service
    ports:
      - "5005:5005"
    env_file: .env
    restart: always

  admin-service:
    build: ./admin-service
    image: backend-admin-service
    container_name: minit-admin-service
    ports:
      - "5006:5006"
    env_file: .env
    depends_on:
      - auth-service
    restart: always

  gateway-service:
    build: ./gateway-service
    image: backend-gateway-service
    container_name: minit-gateway-service
    ports:
      - "5000:5000"
    restart: always

